apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: intel-dsa-plugin
spec:
  template:
    spec:
      initContainers:
      - name: intel-dsa-initcontainer
        image: intel/intel-dsa-initcontainer:0.22.0
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /sys/devices
          name: sys-devices
      volumes:
      - name: sys-devices
        hostPath:
          path: /sys/devices
