apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: intel-qat-plugin
  labels:
    app: intel-qat-plugin
spec:
  selector:
    matchLabels:
      app: intel-qat-plugin
  template:
    metadata:
      labels:
        app: intel-qat-plugin
    spec:
      containers:
      - name: intel-qat-plugin
        image: intel/intel-qat-plugin:0.23.0
        securityContext:
          readOnlyRootFilesystem: true
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: devdir
          mountPath: /dev/vfio
          readOnly: true
        - name: pcidir
          mountPath: /sys/bus/pci
        - name: kubeletsockets
          mountPath: /var/lib/kubelet/device-plugins
      volumes:
      - name: devdir
        hostPath:
          path: /dev/vfio
      - name: pcidir
        hostPath:
          path: /sys/bus/pci
      - name: kubeletsockets
        hostPath:
          path: /var/lib/kubelet/device-plugins
      nodeSelector:
        kubernetes.io/arch: amd64
